security:
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER 
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: UserBundle:User
                property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            #provider: in_memory
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /


    
    access_control:
        - { path: ^/backend, roles: ROLE_ADMIN }
