adduser:
    path: /subscribe
    defaults:
        _controller: UserBundle:Security:addUser

login:
    path: /login
    defaults: { _controller: UserBundle:Security:login}

login_check:
    path: /login_check
    defaults: 
        _controller: UserBundle:Security:loginCheck

logout:
    path: /logout
    defaults:
        _controller: UserBundle:Security:logout
