homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

backend:
    path: /backend
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Backend/index.html.twig


pool_video_manage:
    path:     /backend/pool_video
    defaults: { _controller: AppBundle:Backend:managePoolVideo }

pool_video_add:
    path: /backend/pool_video/add
    defaults:
        _controller: AppBundle:Backend:addPoolVideo

pool_video_modif:
    path: /backend/pool_video/modif/{id}
    defaults:
        _controller: AppBundle:Backend:modifPoolVideo
    requirements:
        id: '\d+'

pool_video_delete:
    path: /backend/pool_video/delete/{id}
    defaults:
        _controller: AppBundle:Backend:deletePoolVideo
    requirements:
        id: '\d+'



video_manage:
    path: /backend/video
    defaults:
        _controller: AppBundle:Backend:manageVideo

video_add:
    path: /backend/video/add
    defaults:
        _controller: AppBundle:Backend:addVideo

video_modif:
    path: /backend/video/modif/{id}
    defaults:
        _controller: AppBundle:Backend:modifVideo
    requirements:
        id: '\d+'

video_delete:
    path: /backend/video/delete/{id}
    defaults:
        _controller: AppBundle:Backend:deleteVideo
    requirements:
        id: '\d+'



platform:
    path: /platform
    defaults:
        _controller: FrameworkBundle:Template:template
        template: Platform/index.html.twig